version: '3'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./tools/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../logs/psql/data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - auth

  auth:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "2000:2000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - auth

networks:
  auth:
    external: true
